version: '3.7'

services:
  web:
    build:
      context: .
    container_name: sqlite-todo
    environment:
      VIRTUAL_HOST: todo.docker
    network_mode: bridge
    volumes:
      - ./code:/var/www/html
